workspace:
  base: /go

pipeline:
  test:
    image: golang:1.8.3
    environment:
      - CGO_ENABLED=0
    commands:
      - go build -ldflags "-s -w" -a -tags netgo

  publish:
    image: plugins/docker:latest
    repo: bclermont/drone-debug
    tags:
      - latest
    when:
      branch: master
      event: push

plugin:
  name: Debug
  desc: Describe build environment (files and environment variables)
  type: clone
  image: bclermont/drone-debug
  labels:
    - dev
